version: '3.2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: your-password-here
      POSTGRES_USER: your-username-here
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
